NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

In [9]:
!pip install numpy

Defaulting to user installation because normal site-packages is not writeable



[notice] A new release of pip is available: 24.1.2 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [30]:
# [], (), {}  - list, tuple, dictionary

import numpy as np

# Creating array using numpy
# Creating 1D one dimensional array
arr1=np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
arr1.shape

[1 2 3 4 5]
<class 'numpy.ndarray'>


(5,)

In [11]:
## 1D array
arr2=np.array([1,2,3,4,5])
arr2.reshape(1,5)


array([[1, 2, 3, 4, 5]])

In [12]:
arr2=np.array([[1,2,3,4,5]])
arr2.shape

(1, 5)

In [13]:
# creating 2D array
arr2=np.array([[1,2,3,4,5], [6,7,8,9,10], [11,12,13,14,15]])
print(arr2)
arr2.shape

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


(3, 5)

In [23]:
# Creating dynamic data
np.arange(0,25).reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [24]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [29]:
np.ones((5,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [35]:
arr=np.array([[1,2,3], [4,5,6]])
print("Array - ", arr)
print("Shape - ", arr.shape)
print("Number of Dimensions - ", arr.ndim)
print("Size - ", arr.size)
print("data type - ", arr.dtype)

Array -  [[1 2 3]
 [4 5 6]]
Shape -  (2, 3)
Number of Dimensions -  2
Size -  6
data type -  int64


In [41]:
# Numpy Vectorized Operations
arr1=np.array([[1,2,3,4,5]])
arr2=np.array([[10,20,30,40,50]])

print("Addition - ", arr1+arr2)
print("Subtraction - ", arr2-arr1)
print("Multiplication - ", arr1*arr2)
print("Division - ", arr2/arr1)



Addition -  [[11 22 33 44 55]]
Subtraction -  [[ 9 18 27 36 45]]
Multiplication -  [[ 10  40  90 160 250]]
Division -  [[10. 10. 10. 10. 10.]]


In [43]:
# Universal functions
arr=np.array([[1,2,3,4,5]])

# square root
print(np.sqrt(arr))

# exponential
print(np.exp(arr))


[[1.         1.41421356 1.73205081 2.         2.23606798]]
[[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]]


In [50]:
arr2=np.array([[1,2,3,4,5], [6,7,8,9,10], [11,12,13,14,15]])
print(arr2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [60]:
# slicing getting data
print(arr2[1:2,0:2])
arr2.shape

[[6 7]]


(3, 5)

In [66]:
print(arr2[1:,0:2])
arr2.shape

[[ 6  7]
 [11 12]]


(3, 5)

In [67]:
print(arr2[1:2,0:1])
arr2.shape

[[6]]


(3, 5)

In [68]:
# setting the data
arr2[1:2,2]=100
print(arr2)

[[  1   2   3   4   5]
 [  6   7 100   9  10]
 [ 11  12  13  14  15]]


In [69]:
arr2[1:]=100
print(arr2)

[[  1   2   3   4   5]
 [100 100 100 100 100]
 [100 100 100 100 100]]


In [76]:
np.max(arr2)

np.int64(100)

In [77]:
np.min(arr2)

np.int64(1)

In [84]:
data=np.array([1,2,3,4,5,6,7,8,9,10])
data[(data>=5) & (data<=8)] 

array([5, 6, 7, 8])